# Generated by Django 3.2.9 on 2021-12-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='sub1',
        ),
        migrations.AddField(
            model_name='test',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
